apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-deployment
  labels:
    helm.sh/chart: {{ include "ambassador.chart" . }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: ambassador
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: ambassador
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        consul.hashicorp.com/connect-inject: "false"
        # see: https://github.com/helm/charts/tree/master/stable/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8877"
      labels:
        app: ambassador
        service: ambassador
        public: "yes"
        netnolimit: "yes"
        userhelper: "yes"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  service: ambassador
              topologyKey: kubernetes.io/hostname
      serviceAccountName: ambassador
      securityContext:
        runAsUser: 8888
        #fsGroup: 2000
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/datawire/ambassador:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
          - name: AMBASSADOR_NAMESPACE
            value: {{ .Values.userNamespace | quote }}
          - name: AMBASSADOR_SINGLE_NAMESPACE
            value: "true"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: admin
              containerPort: 8877
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

