# Default values for manifestservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

selectorLabels:
  app: manifestservice
  release: production

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations: {}
  name: ""


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

labels:
  s3: "yes"
  public: "yes"
  userhelper: "yes"
  #GEN3_DATE_LABEL

automountServiceAccountToken: false

resources:
  requests:
    cpu: 0.5
    memory: 512Mi
  limits:
    cpu: 1.0
    memory: 1024Mi

manifestserviceG3auto:
  hostname: testinstall
  bucketName: testbucket
  prefix: test
  awsaccesskey: ""
  awssecretkey: ""
