remote: origin
target-branch: master
chart-dirs:
  - helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: true
debug: false
validate-maintainers: false