apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicom-viewer-deployment
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dicom-viewer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "dicom-viewer.selectorLabels" . | nindent 6 }}
      release: "production"
      public: "yes"
  template:
    metadata:
      labels:
        {{- include "dicom-viewer.selectorLabels" . | nindent 8 }}
        release: "production"
        public: "yes"
    spec:
      containers:
        - name: "dicom-viewer"
          image: "quay.io/cdis/ohif-viewer:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          readinessProbe: 
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 30
          livenessProbe: 
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30
          ports:
            - containerPort: 80
