apiVersion: v1
kind: Service
metadata:
  name: "pidgin-service"
  labels:
    {{- include "pidgin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pidgin.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      name: http
    - protocol: TCP 
      port: 443 
      targetPort: 443
      name: https
  type: ClusterIP