#Deployment
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

#Configuration values for Orthanc. To see how these values correspond to configuration values for 
#Orthanc, take a look at the config-volume-g3auto file, where these values are used. 
config:
  authenticationEnabled: false
  enableIndex: true
  enableStorage: true
  port: "5432"
  host: postgres-postgresql.postgres.svc.cluster.local
  dataBase: postgres
  userName: postgres
  password: postgres
  indexConnectionsCount: 5
  lock: false
