apiVersion: v1
kind: Service
metadata:
  name: "guppy-service"
  labels:
    {{- include "guppy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "guppy.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP