apiVersion: v1
kind: Secret
metadata:
  name: ohdsi-webapi-config
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
type: Opaque
stringData:
  datasource_driverClassName: org.postgresql.Driver
  datasource_url: {{ include "databaseURL" .}}
  datasource_ohdsi_schema: ohdsi
  datasource_username: {{ .Values.webAPI.dbUser }}
  datasource_password: {{ .Values.webAPI.dbPassword }}
  spring_jpa_properties_hibernate_default_schema: ohdsi
  spring_jpa_properties_hibernate_dialect: org.hibernate.dialect.PostgreSQLDialect
  spring_batch_repository_tableprefix: ohdsi.BATCH_
  flyway_datasource_driverClassName: org.postgresql.Driver
  flyway_datasource_url: {{ include "databaseURL" .}}
  flyway_schemas: ohdsi
  flyway_placeholders_ohdsiSchema: ohdsi
  flyway_datasource_username: {{ .Values.webAPI.dbUser }}
  flyway_datasource_password: {{ .Values.webAPI.dbPassword }}
  flyway_locations: classpath:db/migration/postgresql
  
  # Zoe testing Atlas-Fence
  security_cors_enabled: "true"
  security_origin: "*"
  security_token_expiration: "43200"
  security_ssl_enabled: "false"

#  security_provider: DisabledSecurity
  security_provider: AtlasRegularSecurity

  security_auth_windows_enabled: "false"
  security_auth_kerberos_enabled: "false"
  security_auth_openid_enabled: "true"
  security_auth_facebook_enabled: "false"
  security_auth_github_enabled: "false"
  security_auth_google_enabled: "false"
  security_auth_jdbc_enabled: "false"
  security_auth_ldap_enabled: "false"
  security_auth_ad_enabled: "false"
  security_auth_cas_enabled: "false"

  security_db_datasource_schema: security
  security_db_datasource_url: {{ include "databaseURL" .}}
  security_db_datasource_driverClassName: org.postgresql.Driver
  security_db_datasource_username: {{ .Values.webAPI.dbUser }}
  security_db_datasource_password: {{ .Values.webAPI.dbPassword }}

  security_oid_clientId: {{ .Values.webAPI.fenceClientID }}
  security_oid_apiSecret: {{ .Values.webAPI.fenceClientSecret }}
  security_oid_url: https://{{ .Values.webAPI.hostname }}/.well-known/openid-configuration
  security_oid_redirectUrl: https://atlas.{{ .Values.webAPI.hostname }}/atlas/#/welcome
  security_oid_logoutUrl: https://atlas.{{ .Values.webAPI.hostname }}/atlas/#/home

  security_oauth_callback_ui: https://atlas.{{ .Values.webAPI.hostname }}/atlas/#/welcome
  security_oauth_callback_api: https://atlas.{{ .Values.webAPI.hostname }}/WebAPI/user/oauth/callback
  security_oauth_callback_urlResolver: query

  logging_level_root: info
  logging_level_org_ohdsi: info
  logging_level_org_apache_shiro: info