apiVersion: v1
kind: Service
metadata:
  name: "argo-wrapper-service"
  labels:
    {{- include "argo-wrapper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "argo-wrapper.selectorLabels" . | nindent 4 }}
