# Default values for revproxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  aws:
    enabled: false
    account:
  dev: true
  postgres:
    db_create: true
    master:
      host:
      username: postgres
      password:
      port: "5432"
  environment: default
  hostname: localhost
  revproxyArn: arn:aws:acm:us-east-1:123456:certificate
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
  portalApp: gitops
  kubeBucket: kube-gen3
  logsBucket: logs-gen3
  syncFromDbgap: false
  userYamlS3Path: s3://cdis-gen3-users/test/user.yaml
  publicDataSets: true
  tierAccessLevel: libre
  netPolicy: true
  dispatcherJobNum: 10
  ddEnabled: false


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

resources: 
  # TODO: revaluate thse
  requests:
    cpu: 0.5
    memory: 1024Mi
  limits:
    cpu: 1.0
    memory: 2048Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#TODO Figure out what this is doing, and how to explain it
userhelperEnabled: false

revproxyElb:
  sslCert: ""
  targetPortHTTPS: 443
  targetPortHTTP: 80

  gen3SecretsFolder: Gen3Secrets
