apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicom-server-deployment
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dicom-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "dicom-server.selectorLabels" . | nindent 6 }}
      release: "production"
      public: "yes"
  template:
    metadata:
      labels:
        {{- include "dicom-server.selectorLabels" . | nindent 8 }}
        release: "production"
        public: "yes"
    spec:
      volumes:
        - name: config-volume-g3auto
          secret:
            secretName: orthanc-g3auto
      containers:
        - name: "dicom-server"
          image: "quay.io/cdis/gen3-orthanc:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          readinessProbe: 
            httpGet:
              path: /system
              port: 8042
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 30
          livenessProbe: 
            httpGet:
              path: /system
              port: 8042
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30 
          ports:
            - containerPort: 8042
          volumeMounts:
            - name: config-volume-g3auto
              readOnly: true
              mountPath: /etc/orthanc/orthanc_config_overwrites.json
              subPath: orthanc_config_overwrites.json