apiVersion: apps/v1
kind: Deployment
metadata:
  name: tube-deployment
  labels:
    {{- include "tube.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "tube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tube.labels" . | nindent 8 }}
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: tube
          image: "quay.io/cdis/tube:2021.12"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              python run_config.py
              while true; do sleep 5; done
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
