apiVersion: apps/v1
kind: Deployment
metadata:
  name: hatchery-deployment
  labels:
    {{- include "hatchery.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hatchery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hatchery.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: hatchery-config
          configMap:
            name: manifest-hatchery
      serviceAccountName: hatchery-service-account
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "quay.io/cdis/hatchery:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: http
          readinessProbe:
            httpGet:
              path: /_status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HTTP_PORT
              value: "8000"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GEN3_ENDPOINT
              value: {{ .Values.global.hostname }}
            - name: GEN3_VPCID
              value: {{ .Values.global.vpcid }}
          volumeMounts:
            - name: hatchery-config
              readOnly: true
              mountPath: /hatchery.json
              subPath: json