apiVersion: v1
kind: Service
metadata:
  name: hatchery-service
  labels:
    {{- include "hatchery.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hatchery.selectorLabels" . | nindent 4 }}
