apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexd-deployment
  labels:
    {{- include "indexd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "indexd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "indexd.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: "indexd-secret"
        - name: creds-volume
          secret:
            secretName: "indexd-creds"
      serviceAccountName: {{ include "indexd.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/cdis/indexd:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: "GEN3_DEBUG"
              value: "false"
          volumeMounts:
            - name: "config-volume"
              readOnly: true
              mountPath: "/var/www/indexd/local_settings.py"
              subPath: "local_settings.py"
            - name: "creds-volume"
              readOnly: true
              mountPath: "/var/www/indexd/creds.json"
              subPath: creds.json
            - name: "config-volume"
              readOnly: true
              mountPath: "/var/www/indexd/config_helper.py"
              subPath: config_helper.py
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: indexd-init
          image: "quay.io/cdis/indexd:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/bash" ]
          args: 
            - "-c"
            # Script always succeeds if it runs (echo exits with 0)
            # indexd image does not include jq, so use python 
            - |
              eval $(python 2> /dev/null <<EOM
              import json

              # sheepdog_data = json.load(open('/var/www/indexd/sheepdog_creds.json', 'r'))
              indexd_data = json.load(open('/var/www/indexd/creds.json', 'r'))
              user_db = { 'gdcapi': 'indexd_password' }
              if 'user_db' in indexd_data:
                more_users = indexd_data['user_db']
                for user in more_users:
                  user_db[user] = more_users[user]
              print('declare -A user_db')
              for user in user_db:
                print("user_db['%s']='%s'" % (user, user_db[user]))
              EOM
              )
              for user in "${!user_db[@]}"; do
                python /indexd/bin/index_admin.py create --username "$user" --password "${user_db[$user]}"
              done
              echo "Exit code: $?"
          volumeMounts:
            {{- toYaml .Values.initVolumeMounts | nindent 12 }}
          env:
            {{ toYaml .Values.initEnv | nindent 12 }}

