# Default values for hatchery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

resources: 
  requests:
    cpu: 0.5
    memory: 1024Mi
  limits:
    cpu: 1.0
    memory: 2400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
