# Default values for guppy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Deployment
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
dataDog:
  enabled: false
  env: dev

automountServiceAccountToken: false

# Environment Variables
esEndpoint: esproxy-service:9200
arboristUrl: http://arborist-service
tierAccessLevel: regular
# acceptable values for `tier_access_level` are: `libre`, `regular` and `private`. If omitted, by default common will be treated as `private`
tierAccessLimit: 1000
# Placeholders for datadog
ddTraceEnabled:
ddEnv:
ddService:
ddVersion:
ddLogsInjection:
ddProfilingEnabled:
ddTraceSampleRate:
ddTraceAgentHostname:

resources:
  requests:
    cpu: 0.5
    memory: 1024Mi
  limits:
    cpu: 1
    memory: 2400Mi


#Configmap
indices: 
- index: dev_case
  type: case
- index: dev_file
  type: file
configIndex: dev_case-array-config
authFilterField: auth_resource_path
enableEncryptWhitelist: true
encryptWhitelist: test1
