# Default values for ssjdispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

selectorLabels:
  app: ssjdispatcher
  release: production

labels:
  netnolimit: "yes"
  public: "yes"

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ssjdispatcher
        topologyKey: "kubernetes.io/hostname"
volumes:
  - name: ssjdispatcher-creds-volume
    secret:
      secretName: "ssjdispatcher-creds"
volumeMounts:
  - name: "ssjdispatcher-creds-volume"
    readOnly: true
    mountPath: "/credentials.json"
    subPath: credentials.json

awsRegion: us-east-1
awsStsRegionalEndpoints: regional
gen3Namespace: default
dispatcherJobNum: "10"

indexing: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexs3client:2022.08

resources:
  requests:
    cpu: 0.1
    memory: 128Mi
  limits:
    cpu: 1.0
    memory: 2400Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

automountServiceAccountToken: true

ssjcreds:
  sqsUrl: "https://sqs.us-east-1.amazonaws.com/12345678901234/test-upload_data_upload"
  jobName: "indexing"
  jobPattern: "s3://test-12345678901234-upload/*"
  jobUrl: "http://indexd-service/index"
  jobUser: "ssj"
  jobPassword: "replace_with_password"
  jobRequestCpu: "500m"
  jobRequestMem: "0.5Gi"
  metadataserviceUrl: "http://revproxy-service/mds"
  metadataserviceUsername: "gateway"
  metadataservicePassword: "replace_with_password"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "ssjdispatcher-service-account"
