apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit.secretName" . }}
  labels:
    {{- include "audit.labels" . | nindent 4 }}
stringData: 
  audit-service-config.yaml: |-
      ####################
      # SERVER           #
      ####################
      # whether to enable debug logs
      DEBUG: {{ .Values.server.debug }}
      PULL_FROM_QUEUE: {{ .Values.server.pull_from_queue }}
      QUEUE_CONFIG:
      type: aws_sqs
      aws_sqs_config:
          sqs_url: {{ .Values.secrets.sqs.url }}
          region: {{ .Values.secrets.sqs.region }}
      ####################
      # DATABASE         #
      ####################
      DB_HOST: {{ include "gen3.service-postgres" (dict "key" "host" "service" $.Chart.Name "context" $) | quote }}
      DB_USER: {{include "gen3.service-postgres" (dict "key" "username" "service" $.Chart.Name "context" $) | quote}}
      DB_PASSWORD:  {{include "gen3.service-postgres" (dict "key" "password" "service" $.Chart.Name "context" $) | quote }}
      DB_DATABASE: {{include "gen3.service-postgres" (dict "key" "database" "service" $.Chart.Name "context" $)| quote }}
