apiVersion: v1
kind: Service
metadata:
  name: audit-service
  labels:
    {{- include "audit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "audit.selectorLabels" . | nindent 4 }}
