{{- range $secretName, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := $secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wts-g3auto
type: Opaque
stringData:
#TODO: Fill in external_oidc in appcreds.json from values.yaml
  appcreds.json: |
    {
      "wts_base_url": "https://{{ .Values.hostname }}/wts/",
      "encryption_key": "{{ .Values.encpryption_key | default (randAlphaNum 32 | b64enc) }}",
      "secret_key": "{{ .Values.secret_key | default (randAlphaNum 32 | b64enc) }}",
      "fence_base_url": "http://fence-service/",
      "oidc_client_id": "{{ .Values.oidc_client_id  | default (randAlphaNum 32) }}",
      "oidc_client_secret": "{{ .Values.oidc_client_secret | default (randAlphaNum 32) }}",
      "external_oidc": []
    }
  dbcreds.json: |
    {
      "db_host": {{ .Values.database.host | quote }},
      "db_username": {{ .Values.database.user | quote}},
      "db_password": {{ include "wts.postgres.password" . | quote }},
      "db_database": {{ .Values.database.dbname | quote }}
    }