# Default values for aws-es-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment
podAnnotations: {"gen3.io/network-ingress": "guppy,metadata,spark,tube"}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

replicaCount: 1

revisionHistoryLimit: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

automountServiceAccountToken: false

volumes:
  - name: credentials
    secret:
      secretName: aws-es-proxy

image:
  repository: quay.io/cdis/aws-es-proxy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

ports:
  - containerPort: 9200

# Environment Variables
esEndpoint: test.us-east-1.es.amazonaws.com


volumeMounts:
  - name: credentials
    readOnly: true
    mountPath: /root/.aws

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 2Gi


# Service and Pod
service:
  type: ClusterIP
  port: 9200

# Secret
secrets:
  awsAccessKeyId: "asdpofasdokj"
  awsSecretAccessKey: "asdfjkljklj"
