# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ambassador-deployment

service:
  type: ClusterIP
  port: 8877

selectorLabels:
  service: ambassador

userNamespace: "jupyter-pods"

resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
