# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ambassador-deployment

service:
  type: ClusterIP
  port: 8877

selectorLabels:
  service: ambassador

userNamespace: "jupyter-pods"

<<<<<<< HEAD
resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 100Mi

=======
>>>>>>> af2c152 (Cleaned up ambassador's values.yaml)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

<<<<<<< HEAD
nodeSelector: {}

tolerations: []

affinity: {}
=======
rbac:
  rbacServiceName: ambassador-admin
  servicePort: 8877
>>>>>>> af2c152 (Cleaned up ambassador's values.yaml)
