apiVersion: v1
kind: Secret
metadata:
  name: aws-config-fence
type: Opaque
stringData:
  credentials: |
        [default]
        aws_access_key_id={{ .Values.global.aws.account.aws_access_key_id  }}
        aws_secret_access_key={{ .Values.global.aws.account.aws_secret_access_key  }}