apiVersion: v1
kind: Secret
metadata:
  name: fence-config
stringData:
  fence-config.yaml: |
    BASE_URL: https://{{ .Values.global.hostname }}/user
    {{- with .Values.FENCE_CONFIG }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fence-sshconfig
data:
  projects.yaml: {{  .Values.sshconfig | default ((.Files.Get "fence-ssh/config")) }}