{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fence.serviceAccountName" . }}
  labels:
    {{- include "fence.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.global.usersync -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usersync-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usersync-job-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: usersync-job-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: usersync-job-role
subjects:
  - kind: ServiceAccount
    name: usersync-job
    namespace: default
{{- end }}
