apiVersion: v1
kind: Service
metadata:
  name: fence-service
  labels:
    {{- include "fence.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fence.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: presigned-url-fence-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: presigned-url-fence

