{{- if .Values.global.usersync -}}
#
# run with:
# gen3 job run usersync
#
# Optional Arguments:
#     ADD_DBGAP Force attempting a dbgap sync if "true", falls back to manifest configuration
#               by defualt. i.e. this isn't required for a dbGaP sync to happen
#               default: "false" - fall back to manifest configuration
#               ex: gen3 job run usersync ADD_DBGAP true
#
#     ONLY_DBGAP Forces ONLY a dbgap sync if "true", IGNORING user.yaml
#                default: "false"
#                ex: gen3 job run usersync ONLY_DBGAP true
#
apiVersion: batch/v1
kind: Job
metadata:
  name: usersync
spec:
  # Kill the job if it has not finished within 4 hours
  activeDeadlineSeconds: 14400
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      serviceAccountName: usersync-job
      volumes:
        - name: user-yaml
          configMap:
            name: useryaml
            items:
              - key: useryaml
                path: user.yaml
        - name: config-volume
          secret:
            secretName: "fence-config"
        - name: creds-volume
          secret:
            secretName: "fence-creds"
        - name: projects
          configMap:
            name: "projects"
        - name: fence-google-app-creds-secret-volume
          secret:
            secretName: "fence-google-app-creds-secret"
        - name: fence-google-storage-creds-secret-volume
          secret:
            secretName: "fence-google-storage-creds-secret"
        - name: shared-data
          emptyDir: {}
        - name: fence-sshconfig
          configMap:
            name: "fence-sshconfig"
      initContainers:
        - name: wait-for-fence
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          args: ["while [ $(curl -sw '%{http_code}' http://fence-service -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for fence...'; done"]
      containers:
      - name: usersync
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        env:
          {{- toYaml .Values.env | nindent 12 }}
        volumeMounts:
          - name: user-yaml
            mountPath: /mnt/shared/user.yaml
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence-config.yaml"
            subPath: fence-config.yaml
          - name: "creds-volume"
            readOnly: true
            mountPath: "/var/www/fence/creds.json"
            subPath: creds.json
          - name: "projects"
            mountPath: "/var/www/fence/projects.yaml"
            subPath: "projects.yaml"
          - name: "fence-google-app-creds-secret-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence_google_app_creds_secret.json"
            subPath: fence_google_app_creds_secret.json
          - name: "fence-google-storage-creds-secret-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence_google_storage_creds_secret.json"
            subPath: fence_google_storage_creds_secret.json
          - name: shared-data
            mountPath: /mnt/shared
          - name: "fence-sshconfig"
            mountPath: "/root/.ssh/config"
            subPath: "config"
        command: ["/bin/bash" ]
        args:
          - "-c"
          # Script always succeeds if it runs (echo exits with 0)
          - |
            echo 'options use-vc' >> /etc/resolv.conf
            sleep 1000
            pip3 install SQLAlchemy==1.3.6
            if [[ "$SYNC_FROM_DBGAP" != True && "$ADD_DBGAP" != "true" ]]; then
              if [[ -f /mnt/shared/user.yaml ]]; then
                echo "running fence-create"
                time fence-create sync --arborist http://arborist-service --yaml /mnt/shared/user.yaml
              else
                echo "/mnt/shared/user.yaml did not appear within timeout :-("
                false  # non-zero exit code
              fi
              exitcode=$?
            else
              output=$(mktemp "/tmp/fence-create-output_XXXXXX")
              if [[ -f /mnt/shared/user.yaml && "$ONLY_DBGAP" != "true" ]]; then
                echo "Running fence-create dbgap-sync with user.yaml - see $output"
                time fence-create sync --arborist http://arborist-service --sync_from_dbgap "True" --projects /var/www/fence/projects.yaml --yaml /mnt/shared/user.yaml 2>&1 | tee "$output"
              else
                echo "Running fence-create dbgap-sync without user.yaml - see $output"
                time fence-create sync --arborist http://arborist-service --sync_from_dbgap "True" --projects /var/www/fence/projects.yaml 2>&1 | tee "$output"
              fi
              exitcode="${PIPESTATUS[0]}"
              echo "$output"
              # Echo what files we are seeing on dbgap ftp to Slack
              # We only do this step every 12 hours and not on weekends to reduce noise
              if [[ -n "$SLACK_SEND_DBGAP" && "$SLACK_SEND_DBGAP" = True ]]; then
                files=$(grep "Reading file" "$output")
                let hour=$(date -u +10#%H)
                let dow=$(date -u +10#%u)
                if ! (( hour % 12 )) && (( dow < 6 )); then
                  if [ "${slackWebHook}" != 'None' ]; then
                    curl -X POST --data-urlencode "payload={\"text\": \"FenceHelper: \n\`\`\`\n${files}\n\`\`\`\"}" "${slackWebHook}"
                  fi
                fi
              fi
            fi
            if [[ $exitcode -ne 0 && "${slackWebHook}" != 'None' ]]; then
              emptyfile=$(grep "EnvironmentError:" "$output")
              if [ ! -z "$emptyfile" ]; then
                curl -X POST --data-urlencode "payload={\"text\": \"JOBSKIPPED: User sync skipped on ${gen3Env} ${emptyfile}\"}" "${slackWebHook}";
              else
                curl -X POST --data-urlencode "payload={\"text\": \"JOBFAIL: User sync failed on ${gen3Env}\"}" "${slackWebHook}"
              fi
            fi
            echo "Exit code: $exitcode"
            exit "$exitcode"
      - name: awshelper
        image: quay.io/cdis/awshelper:master
        imagePullPolicy: Always
        env:
        - name: gen3Env
          valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: hostname
        - name: userYamlS3Path
          valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: useryaml_s3path
        volumeMounts:
          - name: user-yaml
            mountPath: /mnt/shared/user.yaml
          - name: shared-data
            mountPath: /mnt/shared
        command: ["/bin/bash" ]
        args:
          - "-c"
          - |
            GEN3_HOME=/home/ubuntu/cloud-automation
            source "${GEN3_HOME}/gen3/lib/utils.sh"
            gen3_load "gen3/gen3setup"

            echo "awshelper updating etl configmap"
            if ! gen3 gitops etl-convert < /mnt/shared/user.yaml > /tmp/user.yaml; then
              echo "ERROR: failed to generate ETL config"
              exit 1
            fi
            kubectl delete configmap fence > /dev/null 2>&1
            kubectl create configmap fence --from-file=/tmp/user.yaml
            echo "Helper exit ok"
      restartPolicy: Never
{{- end }}