apiVersion: v1
kind: Service
metadata:
  name: "sheepdog-service"
  labels:
    {{- include "sheepdog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "sheepdog.selectorLabels" . | nindent 4 }}
