apiVersion: v1
kind: Secret
metadata:
  name: sheepdog-secret
type: Opaque
data:
{{ (.Files.Glob "sheepdog-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sheepdog-creds
type: Opaque
stringData:
  creds.json: |-
    {
      "fence_host": {{ .Values.secrets.fence.host | quote }},
      "fence_username": {{ .Values.secrets.fence.user | quote }},
      "fence_password": {{ include "fence.postgres.password" . | quote }},
      "fence_database": {{ .Values.secrets.fence.database | quote }},

      "db_host": {{ .Values.secrets.sheepdog.host | quote }},
      "db_username": {{ .Values.secrets.sheepdog.user | quote }},
      "db_password": {{ include "sheepdog.postgres.password" . | quote }},
      "db_database": {{ .Values.secrets.sheepdog.database | quote }},

      "gdcapi_secret_key": {{ default (randAlphaNum 50) .Values.secrets.gdcapi.secretKey | quote }},
      "hostname": {{ default "ingress.local" .Values.hostname  | quote}}
    }