apiVersion: apps/v1
kind: Deployment
metadata:
  name: arborist-deployment
  labels:
    {{- include "arborist.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "arborist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arborist.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: creds-volume
        secret:
          secretName: "arborist-dbcreds"
      serviceAccountName: {{ include "arborist.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/cdis/arborist:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["sh"]
          args:
            - "-c"
            - |
              set -e
              # set env vars
              export PGSSLMODE="disable"
              
              # bring the database schema up to the latest version
              /go/src/github.com/uc-cdis/arborist/migrations/latest

              # run arborist
              /go/src/github.com/uc-cdis/arborist/bin/arborist
          env:
            - name: JWKS_ENDPOINT
              value: "http://fence-service/.well-known/jwks"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: arborist-dbcreds
                  key: password
                  optional: false
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: arborist-dbcreds
                  key: username
                  optional: false
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: arborist-dbcreds
                  key: database
                  optional: false
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: arborist-dbcreds
                  key: host
                  optional: false
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: arborist-dbcreds
                  key: port
                  optional: false
            - name: PGSSLMODE
              value: disable