apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssjdispatcher
spec:
  selector:
      {{- with .Values.selectorLabels }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      {{- with .Values.affinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ssjdispatcher
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken}}
      serviceAccountName: {{ include "ssjdispatcher.serviceAccountName" . }}
      volumes:
        - name: ssjdispatcher-creds-volume
          secret:
            secretName: "ssjdispatcher-creds"
      containers:
        - name: ssjdispatcher
          image: "quay.io/cdis/ssjdispatcher:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: "ssjdispatcher-creds-volume"
              readOnly: true
              mountPath: "/credentials.json"
              subPath: credentials.json
          env:
            {{- with .Values.awsRegion  }}
            - name: AWS_REGION
              value: {{ . }}
            {{- end }}
            {{- with .Values.awsStsRegionalEndpoints  }}
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: {{ . }}
            {{- end }}
            {{- with .Values.gen3Namespace  }}
            - name: GEN3_NAMESPACE
              value: {{ . }}
            {{- end }}
            - name: JOB_IMAGES
              valueFrom:
                configMapKeyRef:
                  name: manifest-ssjdispatcher
                  key: job_images
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}