# Default values for argo-wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment
podAnnotations: {"gen3.io/network-ingress": "argo-wrapper"}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

dataDog:
  enabled: false
  env: dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi

#Configmap
scalingGroups:
- user1: "workflow1"
- user2: "workflow2"
- user3: "workflow3"
s3Bucket: "argo-artifact-downloadable"
internalS3Bucket: "argo-internal-bucket"
indexdAdminUser: "fence"
environment: "default"
pvc: "test-pvc"
