apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestor-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "requestor.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        # gen3 networkpolicy labels
        netnolimit: 'yes'
        public: 'yes'
        dbrequestor: 'yes'
      {{- if eq (include "requestor.ddEnabled" . ) "true" }}
        tags.datadoghq.com/service: "requestor"
        # TODO: move this to helpers so we can have this populated from a configmap
        tags.datadoghq.com/env: {{ .Values.dataDog.env }}
        tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion }}
      {{- end }}
        {{- include "requestor.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - requestor
            topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      volumes: 
        - name: config-volume
          secret:
            secretName: "requestor-g3auto"
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/cdis/requestor:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env: 
            - name: GEN3_DEBUG
              value: "False"
            {{- with .Values.arboristUrl }}
            - name: ARBORIST_URL
              value: {{ . }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /_status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 80
          ports:
            - containerPort: 80
          volumeMounts:
            - name: "config-volume"
              readOnly: true
              mountPath: "/src/requestor-config.yaml"
              subPath: "requestor-config.yaml"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: requestor-db-migrate
          image: "quay.io/cdis/requestor:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: "config-volume"
              readOnly: true
              mountPath: "/src/requestor-config.yaml"
              subPath: "requestor-config.yaml"
          {{- with .Values.initResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              /env/bin/alembic upgrade head