apiVersion: v1
kind: Service
metadata:
  name: "requestor-service"
  labels:
    {{- include "requestor.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "requestor.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
    port: 80
    targetPort: 80 
    name: http
  type: ClusterIP