apiVersion: v1
kind: Secret
metadata:
  name: portal-config
data:
  {{- if .Values.gitops.createdby }}
  gitops-createdby: |
    {{- .Values.gitops.createdby | nindent 4 }}
  {{- else }}
  gitops-createdby: |
    {{- (.Files.Get "defaults/gitops-createdby.png" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.gitops.css }}
  gitops.css: |
    {{- .Values.gitops.css | b64enc | nindent 4 }}
  {{- else }}
  gitops.css: |
    {{- (.Files.Get "defaults/gitops.css" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.gitops.favicon }}
  gitops-favicon.ico: |
    {{- .Values.gitops.favicon | b64enc | nindent 4 }}
  {{- else }}
  gitops-favicon.ico: |
    {{- (.Files.Get "defaults/gitops-favicon.ico" ) | nindent 4 }}
  {{- end }}
  {{- if .Values.gitops.json }}
  gitops.json: |
    {{- .Values.gitops.json | b64enc | nindent 4 }}
  {{- else }}
  gitops.json: |
    {{- (.Files.Get "defaults/gitops.json" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.gitops.logo }}
  gitops-logo.png: |
    {{- .Values.gitops.logo  | nindent 4 }}
  {{- else }}
  gitops-logo.png: |
    {{- (.Files.Get "defaults/gitops-logo.png" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.lit }}
  lit.jpeg: |
    {{- .Values.lit  | nindent 4 }}
  {{- else }}
  lit.jpeg: |
    {{- (.Files.Get "defaults/lit.jpeg" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.chordstk }}
  chordstk.jpg: |
    {{- .Values.chordstk  | nindent 4 }}
  {{- else }}
  chordstk.jpg: |
    {{- (.Files.Get "defaults/chordstk.jpg" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.chords_logo }}
  chords_logo.jpeg: |
    {{- .Values.chords_logo | nindent 4 }}
  {{- else }}
  chords_logo.jpeg: |
    {{- (.Files.Get "defaults/chords_logo.jpeg" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.logo }}
  logo.png: |
    {{- .Values.logo | nindent 4 }}
  {{- else }}
  logo.png: |
    {{- (.Files.Get "defaults/logo.png" | b64enc) | nindent 4 }}
  {{- end }}
  {{- if .Values.pcorlogo }}
  ospcortf_logo.jpg: |
    {{- .Values.pcorlogo  | nindent 4 }}
  {{- else }}
  ospcortf_logo.jpg: |
    {{- (.Files.Get "defaults/ospcortf_logo.jpg" | b64enc) | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-sponsor-config
data:
{{- range $key, $value := .Values.gitops.sponsors }}
  {{ $key }}: {{ $value  }}
{{- end }}
