apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revproxy
spec:
  rules:
    - host: {{ default .Values.global.hostname .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  revproxy-service
                port:
                  number: 80