apiVersion: v1
kind: Service
metadata:
  name: revproxy-service
  labels:
    {{- include "revproxy.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "revproxy.selectorLabels" . | nindent 4 }}
