apiVersion: v1
kind: Service
metadata:
  name: "esproxy-service"
  labels:
    {{- include "aws-es-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: https
  selector:
    {{- include "aws-es-proxy.selectorLabels" . | nindent 4 }}
